spring:
  application:
    name: eureka-server

server:
  port: 7777

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

    serviceUrl:
      defaultZone: http://localhost:7777/eureka/

