spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      routes:
      # 路由到示例项目的spring-cloud-producer模块
      - id: hello_route
        uri: http://localhost:2222
        predicates:
        - Path= /${server.servlet.context-path}/hello/**
        filters:
        - StripPrefix= 1
      # 集成eureka注册中心的配置示例
      - id: hello_ribbon_route
        uri: http://www.baidu.com
        predicates:
        - Path=/producerInEureka/**
        filters:
        - StripPrefix=1
        # 路由到eureka监控页面
      - id: baidu_route
        uri: http://localhost:7777
        predicates:
        - Path=/eureka/**
        filters:
        - StripPrefix=1

server:
  port: 8888
  servlet:
    context-path: producer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7777/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug


