#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: http://git.oschina.net/didispace/SpringCloud-Learning/
#          search-paths: Chapter1-1-8/config-repo
#          username: username
#          password: password

#config server \u9ED8\u8BA4\u4ECE\u672C\u5730src/main/resource\u76EE\u5F55\u4E0B\u68C0\u7D22\u914D\u7F6E\u6587\u4EF6
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:F:/properties #\u6307\u5B9A\u914D\u7F6E\u6587\u4EF6\u4F4D\u7F6E

