spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shaweiwei/myspringcloudconfig/
          search-paths: myconfigpath
          username:
          password:
      label: master
  application:
    name: config-server

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:F:/config.properties
#        default-application-name: config-server
server:
  port: 3333


