spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shoddon/spring-cloud/
          search-paths: root
          username: shoddon@163.com
          password: shoddon@163.com
      label: master
  application:
    name: config-server

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:F:/config.properties
#        default-application-name: config-server
server:
  port: 3333


