#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: http://git.oschina.net/didispace/SpringCloud-Learning/
#          search-paths: Chapter1-1-8/config-repo
#          username: username
#          password: password

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:F:/properties
        default-application-name: config-server
server:
  port: 3333


