spring:
  application:
    name: provider-server
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: eureka-server

server:
  port: 2222

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka

